openshift_cluster_content:
- object: project
  content:
  - name: "CREATE SMOKE TEST PROJECT"
    file: "{{role_path}}/../../applier/SMOKE-TEST/PROJECTS/projects.yml"
    action: create
- object: deployments
  content:
  - name: "DEPLOY SMOKE TEST APP"
    template: "{{role_path}}/../../applier/SMOKE-TEST/TEMPLATES/deployment.yml"
    params: "{{role_path}}/../../applier/SMOKE-TEST/PARAMS/smoke-test.env"
