---
- name: SET GUID ENV VARIABLE
  shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc
  tags: set-guid

- name: DOCKER INSTALLATION VERIFICATION
  yum:
    name: docker
    state: present
  when: "'nodes' in group_names"
  tags: verify-docker

- name: DOCKER CONFIGURATION
  shell: systemctl restart docker
  when: "'nodes' in group_names"
  tags: verify-docker

- name: CHECK NFS PACKAGES NFS-UTILS RPCBIND IN NFS NODES
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-utils
    - rpcbind
  when: "'nfs' in group_names"
  tags: verify-nfs

- name: EXPORTFS CHECKS
  shell : exportfs
  when: "'nfs' in group_names"
  tags: verify-nfs
