---
- name: ADD LOCALHOST TO SEED HOSTS
  add_host:
    hostname: localhost
    groups:
      - seed-hosts
    ansible_connection: local
    ansible_host: localhost

- name: LOAD INVENTORY INFO FROM SEED HOSTS
  include_vars:
    dir: vars
    files_matching: seed-hosts.yml

- name: CREATE APPS AND OCP OBJECTS
  import_role:
    name: OPENSHIFT-APPLIER
  when: "inventory_hostname == 'localhost'"
